# FROM maven:3.6.0-jdk-11-slim AS build
# COPY src /home/app/src
# COPY pom.xml /home/app
# RUN mvn -f /home/app/pom.xml clean test package
#
# FROM openjdk:8-jdk-alpine
# ARG JAR_FILE=/home/app/target/*.jar
# COPY --from=build ${JAR_FILE} app.jar
# ENTRYPOINT ["java","-jar","/app.jar"]

## Used as dockerfile if you select to build from a dockerfile rather than from GIT, and auto detect java